[package]
name = "sealable-trie"
version = "0.0.0"
edition = "2021"

[dependencies]
base64.workspace = true
derive_more.workspace = true
sha2.workspace = true
strum.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rand.workspace = true
