# binop_separator = "Back"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 3
# brace_style = "PreferSameLine"
# color = "Auto"
# condense_wildcard_suffixes = true
# fn_single_line = true
# format_macro_matchers = true
# format_strings = true
# group_imports = "StdExternalCrate"
# normalize_doc_attributes = true
# overflow_delimited_expr = true

max_width = 80
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
