[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_ibc = "9fd7GDygnAmHhXDVWgzsfR6kSRvwkxVnsY8SaSpSH4SX"

[programs.localnet]
solana_ibc = "9fd7GDygnAmHhXDVWgzsfR6kSRvwkxVnsY8SaSpSH4SX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["solana/solana-ibc/programs/solana-ibc"]

[scripts]
test = "cargo test --lib -- --nocapture --include-ignored ::anchor"
