[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bridge-escrow = "A5ygmioT2hWFnxpPapY3XyDjwwfMDhnSP1Yxoynd5hs4"
restaking = "7WPkwv14yz3ZZnvcYDASeMqmW6zBvssTCj7j13w3G6Km"
solana_ibc = "7MB44vWpnu8X8xH4jLaqeaaaAbt4C7XRUmSSq7WBzqhP"

[programs.localnet]
bridge-escrow = "A5ygmioT2hWFnxpPapY3XyDjwwfMDhnSP1Yxoynd5hs4"
restaking = "7WPkwv14yz3ZZnvcYDASeMqmW6zBvssTCj7j13w3G6Km"
solana_ibc = "7MB44vWpnu8X8xH4jLaqeaaaAbt4C7XRUmSSq7WBzqhP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dorayaki/.config/solana/id.json"

[workspace]
members = ["solana/bridge-escrow/programs/bridge-escrow", "solana/restaking/programs/restaking", "solana/solana-ibc/programs/solana-ibc"]

[scripts]
test = "./solana-test.sh"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
