[features]
seeds = false
skip-lint = false

[programs.devnet]
restaking = "8n3FHwYxFgQCQc2FNFkwDUf9mcqupxXcCvgfHbApMLv3"
solana_ibc = "7uvnkZxh7Z1wwVFMQ1ak7u4LXWx9f8tkgUnMMyiZrSZb"

[programs.localnet]
restaking = "8n3FHwYxFgQCQc2FNFkwDUf9mcqupxXcCvgfHbApMLv3"
solana_ibc = "7uvnkZxh7Z1wwVFMQ1ak7u4LXWx9f8tkgUnMMyiZrSZb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/dhruvjain/.config/solana/id.json"

[workspace]
members = ["solana/restaking/programs/restaking", "solana/solana-ibc/programs/solana-ibc"]

[scripts]
test = "./solana-test.sh"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
