[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_ibc = "EnfDJsAK7BGgetnmKzBx86CsgC5kfSPcsktFCQ4YLC81"

[programs.devnet]
solana_ibc = "EnfDJsAK7BGgetnmKzBx86CsgC5kfSPcsktFCQ4YLC81"

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
  "solana/solana-ibc/programs/solana-ibc"
]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "cargo test --lib -- --nocapture --include-ignored ::anchor"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"
