[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bridge-escrow-rollup = "A5ygmioT2hWFnxpPapY3XyDjwwfMDhnSP1Yxoynd5hs4"
restaking-rollup = "Bq1ZRagd3B5cE48TcnEaJBEByVYBYDTtJYe2HQRHqcmx"
solana_ibc = "7AU8dnzVw6TV9JyQ7dXX4XpRaQSJALTBwjwUiJKCW1kg"

[programs.localnet]
bridge-escrow-rollup = "A5ygmioT2hWFnxpPapY3XyDjwwfMDhnSP1Yxoynd5hs4"
restaking = "Bq1ZRagd3B5cE48TcnEaJBEByVYBYDTtJYe2HQRHqcmx"
solana_ibc = "7AU8dnzVw6TV9JyQ7dXX4XpRaQSJALTBwjwUiJKCW1kg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dorayaki/.config/solana/id.json"

[workspace]
members = ["solana/bridge-escrow-rollup/programs/bridge-escrow-rollup", "solana/restaking/programs/restaking", "solana/solana-ibc/programs/solana-ibc"]

[scripts]
test = "./solana-test.sh"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
