[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_ibc = "32hX7oFAPd2tipkZ8gMUPTsTtRnvJG2fcy9qqhjxVSWh"

[programs.localnet]
solana_ibc = "32hX7oFAPd2tipkZ8gMUPTsTtRnvJG2fcy9qqhjxVSWh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvjain/.config/solana/id.json"

[workspace]
members = ["solana/solana-ibc/programs/solana-ibc"]

[scripts]
test = "cargo test --lib -- --nocapture --include-ignored ::anchor"
