[workspace.package]
version = "0.0.0"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
edition = "2021"
rust-version = "1.71.0"

[workspace]
members = [
    "common/*",
    "solana/restaking/programs/*",
    "solana/trie",
    "solana/trie-example",
    "solana/write-account",
    "solana/solana-ibc/programs/*",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
ahash = "0.8.6"
anchor-lang = {version = "0.29.0", features = ["init-if-needed"]}
anchor-spl = "0.29.0"
ascii = "1.1.0"
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
borsh = { version = "0.10.3", default-features = false }
prost = { version = "0.12.3", default-features = false }
prost-build = { version = "0.12.3", default-features = false }
bytemuck = { version = "1.14", default-features = false }
derive_more = "0.99.17"
hex-literal = "0.4.1"
ibc = { version = "0.50.0", default-features = false, features = ["borsh", "serde"] }
ibc-core-channel-types = { version = "0.50.0", default-features = false }
ibc-core-client-context = { version = "0.50.0", default-features = false }
ibc-core-client-types = { version = "0.50.0", default-features = false }
ibc-core-commitment-types = { version = "0.50.0", default-features = false }
ibc-core-connection-types = { version = "0.50.0", default-features = false }
ibc-core-host = { version = "0.50.0", default-features = false }
ibc-core-host-types = { version = "0.50.0", default-features = false }
ibc-primitives = { version = "0.50.0", default-features = false }
ibc-proto = { version = "0.41.0", default-features = false }
ibc-testkit = { version = "0.50.0", default-features = false }
insta = { version = "1.34.0" }
# https://github.com/contain-rs/linear-map/pull/38 adds no_std support
linear-map = { git = "https://github.com/contain-rs/linear-map", rev = "57f1432e26ff902bc883b250a85e0b5716bd241c", default-features = false }
pretty_assertions = "1.4.0"
primitive-types = "0.12.2"
rand = { version = "0.8.5" }
serde = "1"
serde_json = "1"
sha2 = { version = "0.10.7", default-features = false }
solana-client = "1.17.7"
solana-program = "1.17.7"
solana-sdk = "1.17.7"
spl-associated-token-account = "2.2.0"
spl-token = "4.0.0"
strum = { version = "0.25.0", default-features = false, features = ["derive"] }
uint = "0.9.5"

blockchain = { path = "common/blockchain" }
lib = { path = "common/lib" }
memory = { path = "common/memory" }
sealable-trie = { path = "common/sealable-trie" }
solana-ibc = { path = "solana/solana-ibc/programs/solana-ibc" }
solana-trie = { path = "solana/trie" }
stdx = { path = "common/stdx" }
trie-ids = { path = "common/trie-ids" }

# dev-dependencies
anchor-client = "0.29.0"
anyhow = "1.0.32"

[patch.crates-io]
# aes-gcm-siv 0.10.3 and curve25519-dalek 3.x pin zeroize to <1.4
# which conflicts with other dependencies requiring zeroize ^1.5.
# We’re patching both crates to unpin zeroize.
#
# For aes-gcm-siv we’re using the same revision Solana uses in
# an (as of now) unreleased commit, see
# https://github.com/solana-labs/solana/commit/01f1bf27994d9813fadfcd134befd3a449aaa0bd
#
# For curve25519-dalek we’re using commit from a PR, see
# https://github.com/dalek-cryptography/curve25519-dalek/pull/606
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef" }
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", rev = "8274d5cbb6fc3f38cdc742b4798173895cd2a290" }

# eyre has a mutable global variable which is something Solana
# programs cannot have.  tendermint 0.34 enables eyre unconditionally;
# version which doesn’t do that hasn’t been released yet so we need to
# refer to a commit on master.
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", rev = "37822e540e272d2ca9e763769ad20c581203ff9a" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "37822e540e272d2ca9e763769ad20c581203ff9a" }
