[workspace.package]
version = "0.0.0"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
edition = "2021"
rust-version = "1.71.0"

[workspace]
members = [
    "common/*",
    "solana/trie",
    "solana/trie-example",
    "solana/solana-ibc/programs/*",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = {version = "0.28.0", features = ["init-if-needed"]}
anchor-spl = "0.28.0"
uint = "0.9.5"
ascii = "1.1.0"
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
borsh = { version = "0.10.3", default-features = false }
bytemuck = { version = "1.14", default-features = false }
derive_more = "0.99.17"
hex-literal = "0.4.1"
ibc = { version = "0.47.0", default-features = false, features = ["serde", "borsh"] }
ibc-proto = { version = "0.37.1", default-features = false, features = ["serde"] }
pretty_assertions = "1.4.0"
rand = { version = "0.8.5" }
serde = "1"
serde_json = "1"
sha2 = { version = "0.10.7", default-features = false }
solana-client = "1.16.14"
solana-program = "1.16.14"
solana-sdk = "1.16.14"
strum = { version = "0.25.0", default-features = false, features = ["derive"] }
spl-associated-token-account = "2.2.0"
primitive-types = "0.12.2"

blockchain = { path = "common/blockchain" }
lib = { path = "common/lib" }
memory = { path = "common/memory" }
sealable-trie = { path = "common/sealable-trie" }
solana-trie = { path = "solana/trie" }
stdx = { path = "common/stdx" }

# dev-dependencies
anchor-client = "0.28.0"
anyhow = "1.0.32"

[patch.crates-io]
aes-gcm-siv = { git = "https://github.com/dhruvja/AEADs", branch = "main-aes-gcm-siv-v0.10.3" }
curve25519-dalek = { git = "https://github.com/dhruvja/curve25519-dalek", branch = "master" }

# eyre has a mutable global variable which is something Solana
# programs cannot have.  tendermint crate enables eyre; patch it to
# version that doesn’t do that.
tendermint = { git = "https://github.com/mina86/tendermint-rs.git", branch = "34.0-sans-eyre" }
