[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[bans]
# solana-program is weird and has bunch of duplicate dependencies.
# For now allow duplicates.  TODO(mina86): Figure out if there’s
# something better we can do.
#multiple-versions = "deny"
skip = [
    # derive_more still uses old syn
    { name = "syn", version = "1.0.*" },
]
