[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[bans]
multiple-versions = "deny"
skip = [
    # derive_more still uses old syn
    { name = "syn", version = "1.0.*" },
]
