[package]
name = "stdx"
version = "0.0.0"
edition = "2021"

# [dependencies]
# The crate should have no dependencies.  The idea behind it is to include code
# which depends on the standard library only.
