[package]
name = "solana-allocator"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
edition = "2021"
version.workspace = true

[target.'cfg(target_os = "solana")'.dependencies]
bytemuck.workspace = true
solana-program.workspace = true

[dev-dependencies]
bytemuck.workspace = true
