[package]
name = "solana-ibc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_ibc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang.workspace = true
bincode.workspace = true
ibc.workspace = true
ibc-proto.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
anchor-client.workspace = true
anyhow.workspace = true



