[package]
name = "solana-ibc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_ibc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
mocks = ["ibc/mocks", "ibc/std"]

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
uint.workspace = true
base64.workspace = true
bytemuck.workspace = true
derive_more.workspace = true
ibc-proto.workspace = true
ibc.workspace = true
serde.workspace = true
serde_json.workspace = true
primitive-types.workspace = true
strum.workspace = true
spl-associated-token-account.workspace = true

blockchain.workspace = true
lib.workspace = true
memory.workspace = true
solana-trie.workspace = true
stdx.workspace = true

[dev-dependencies]
anchor-client.workspace = true
anyhow.workspace = true
ibc = { workspace = true, features = ["mocks"] }
