[package]
name = "solana-ibc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_ibc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = {version = "0.28.0", features = ["init-if-needed"]}
bincode = "1.3.3"
ibc = { git = "https://github.com/dhruvja/ibc-rs", features = ["serde", "borsh", "mocks"] }
ibc-proto = { git = "https://github.com/dhruvja/ibc-proto-rs", default-features = false, features = ["serde", "borsh"] }
# ibc = { version = "0.44.1", features = ["serde", "borsh", "mocks"] }
# ibc-proto = { version = "0.34.1", default-features = false, features = ["serde", "borsh"] }
serde = "1"
serde_json = "1"
time = "=0.3.18"
tempfile = "=3.6.0"
getrandom = { version = "0.2.2", features = ["custom"] }

[dev-dependencies]
anchor-client = "0.28.0"
solana-client = { git = "https://github.com/dhruvja/solana", branch = "main-1.16.14" }



