[package]
name = "solana-ibc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_ibc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
mocks = ["ibc-testkit"]

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
base64.workspace = true
bytemuck = { workspace = true, features = ["must_cast"] }
derive_more.workspace = true
ibc-testkit = { workspace = true, optional = true }
ibc.workspace = true
linear-map.workspace = true
primitive-types.workspace = true
serde.workspace = true
serde_json.workspace = true
spl-associated-token-account.workspace = true
spl-token.workspace = true

strum.workspace = true
uint.workspace = true

blockchain.workspace = true
lib.workspace = true
memory.workspace = true
solana-trie.workspace = true
stdx.workspace = true
trie-ids = { workspace = true, features = ["borsh"] }

[dev-dependencies]
anchor-client.workspace = true
anyhow.workspace = true
hex-literal.workspace = true
ibc-testkit.workspace = true
insta.workspace = true

lib = { workspace = true, features = ["test_utils"] }
