[package]
name = "solana-trie"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
version = "0.0.0"
edition = "2021"

[dependencies]
lib.workspace = true
memory.workspace = true
sealable-trie.workspace = true
stdx.workspace = true

[dev-dependencies]
solana-program.workspace = true
