[package]
name = "solana-write-account"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
version = "0.0.0"
edition = "2021"

[lib]
name = "write"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh.workspace = true
solana-program.workspace = true

stdx.workspace = true
