---
name: PR Checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

env:
  SOLANA_VERSION: v1.16.3

jobs:
  misc:
    name: Miscellaneous checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny

      - name: Check bans
        run: cargo-deny --all-features check bans

      - name: Check Clippy (all features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  solana-build: 
    name: Cargo Build using bpf (solana env)
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Install Solana CLI
        run: | 
          set -eux
          curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Run build-bpf
        run: cargo build-sbf

  stable:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Run tests (default features)
        run: cargo test

      - name: Run tests (no default features)
        run: cargo test --no-default-features

      - name: Run tests (all features)
        run: cargo test --all-features

  nightly:
    name: Rust Miri tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri

      - name: Run tests with Miri
        run: cargo miri test -- --skip ::stress_test --skip ::anchor
