---
name: PR Checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

env:
  SOLANA_VERSION: v1.17.7
  ANCHOR_VERSION: 0.29.0

jobs:
  misc:
    name: Miscellaneous checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        id: install-rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny

      - name: Check bans
        run: cargo-deny --all-features check bans

      - name: Check Clippy (all features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

      - name: Cache Anchor
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .avm
            .cargo/bin/avm
            .cargo/bin/anchor
            .config/solana/
            .local/share/solana/
          key: ${{ runner.os }}-${{ steps.install-rust.outputs.cachekey }}-$SOLANA_VERSION-$ANCHOR_VERSION-tools

      - name: Install Solana
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -eux
          curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          cp solana/solana-ibc/keypair.json ~/.config/solana/id.json

      - name: Install Solana PATH
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -eux
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install $ANCHOR_VERSION
          avm use $ANCHOR_VERSION

      - name: Anchor Build
        run: anchor build

      - name: Anchor Build (with mocks)
        run: anchor build -- --features=mocks

  solana-build:
    name: Build SBF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Install Solana CLI
        run: |
          set -eux
          curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          cp solana/solana-ibc/keypair.json ~/.config/solana/id.json

      - name: Run build-sbf
        run: cargo build-sbf

  stable:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Run tests (default features)
        run: cargo test

      - name: Run tests (no default features)
        run: cargo test --no-default-features

      - name: Run tests (all features)
        run: cargo test --all-features

  nightly:
    name: Rust Miri tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri

      - name: Run tests with Miri
        run: cargo miri test -- -Z unstable-options --report-time --skip ::anchor
