---
name: PR Checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  misc:
    name: Miscellaneous checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check bans etc.
      - run cargo deny check advisories ban sources

  stable:
    name: Tests on stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test

  nightly:
    name: Tests on nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri

      - name: Run tests
        run: cargo test

      - name: Run tests with Miri
        run: STRESS_TEST_ITERATIONS=5 cargo miri test
