---
name: Test (with Miri)
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
    miri:
        name: "Miri"
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install Miri
          run: |
            rustup toolchain install nightly --component miri
            rustup override set nightly
            cargo miri setup
        - name: Test with Miri
          run: cargo miri test